export const genres = [
  { gameGenre: "Action" },
  { gameGenre: "Adventure" },
  { gameGenre: "Role-Playing" },
  { gameGenre: "Simulation" },
  { gameGenre: "Strategy" },
  { gameGenre: "Sports" },
  { gameGenre: "Puzzle" },
  { gameGenre: "Idle" },
  { gameGenre: "Survival" },
  { gameGenre: "Horror" },
  { gameGenre: "Platformer" },
  { gameGenre: "Shooter" },
  { gameGenre: "Fighting" },
  { gameGenre: "Stealth" },
  { gameGenre: "Rhythm" },
  { gameGenre: "Visual Novel" },
  { gameGenre: "Interactive Fiction" },
  { gameGenre: "Text Adventure" },
  { gameGenre: "Graphic Adventure" },
  { gameGenre: "Point-and-Click Adventure" },
  { gameGenre: "Tower Defense" },
  { gameGenre: "Real-Time Strategy (RTS)" },
  { gameGenre: "Turn-Based Strategy (TBS)" },
  { gameGenre: "Real-Time Tactics (RTT)" },
  { gameGenre: "Turn-Based Tactics (TBT)" },
  { gameGenre: "4X Strategy (Explore, Expand, Exploit, Exterminate)" },
  { gameGenre: "Massively Multiplayer Online (MMO)" },
  { gameGenre: "MMORPG (Massively Multiplayer Online Role-Playing Game)" },
  { gameGenre: "MOBA (Multiplayer Online Battle Arena)" },
  { gameGenre: "Battle Royale" },
  { gameGenre: "Sandbox" },
  { gameGenre: "Open World" },
  { gameGenre: "Social" },
  { gameGenre: "Educational" },
  { gameGenre: "Exercise" },
  { gameGenre: "Virtual Reality (VR)" },
  { gameGenre: "Augmented Reality (AR)" },
  { gameGenre: "Roguelike" },
  { gameGenre: "Roguelite" },
  { gameGenre: "Soulslike" },
  { gameGenre: "Metroidvania" },
  { gameGenre: "Card Games" },
  { gameGenre: "Board Games" },
  { gameGenre: "Trivia" },
  { gameGenre: "Party" },
  { gameGenre: "Racing" },
  { gameGenre: "Flight Simulator" },
  { gameGenre: "Vehicle Simulator" },
  { gameGenre: "Life Simulation" },
  { gameGenre: "City Building" },
  { gameGenre: "Farming Simulator" },
  { gameGenre: "Management" },
  { gameGenre: "Tycoon" },
  { gameGenre: "Music" },
  { gameGenre: "Dance" },
  { gameGenre: "Karaoke" },
  { gameGenre: "Art" },
  { gameGenre: "Creation" },
  { gameGenre: "Logic" },
  { gameGenre: "Math" },
  { gameGenre: "Word" },
  { gameGenre: "Escape Room" },
  { gameGenre: "Mystery" },
  { gameGenre: "Detective" },
  { gameGenre: "Fantasy" },
  { gameGenre: "Sci-Fi" },
  { gameGenre: "Historical" },
  { gameGenre: "War" },
  { gameGenre: "Post-Apocalyptic" },
  { gameGenre: "Cyberpunk" },
  { gameGenre: "Steampunk" },
  { gameGenre: "Mythology" },
  { gameGenre: "Superhero" },
  { gameGenre: "Zombie" },
  { gameGenre: "Vampire" },
  { gameGenre: "Pirate" },
  { gameGenre: "Ninja" },
  { gameGenre: "Space Opera" },
  { gameGenre: "Love and Romance" },
  { gameGenre: "Comedy" },
  { gameGenre: "Satire" },
  { gameGenre: "Horror Comedy" },
  { gameGenre: "Noir" },
  { gameGenre: "Thriller" },
  { gameGenre: "Espionage" },
  { gameGenre: "Western" },
  { gameGenre: "Martial Arts" },
  { gameGenre: "Anime" },
  { gameGenre: "Retro" },
  { gameGenre: "Experimental" },
  { gameGenre: "Non-Game (Experience)" },
  { gameGenre: "Narrative" },
  { gameGenre: "Environmental" },
  { gameGenre: "Photo and Video" },
  { gameGenre: "Streaming and Broadcasting" },
];

export const getRandomGenre = () => {
  const combineGenres = Math.random() < 0.5;

  if (combineGenres) {
    const randomIndex1 = Math.floor(Math.random() * genres.length);
    const randomIndex2 = Math.floor(Math.random() * genres.length);
    return `${genres[randomIndex1].gameGenre} X ${genres[randomIndex2].gameGenre}`;
  } else {
    const randomIndex = Math.floor(Math.random() * genres.length);
    return genres[randomIndex].gameGenre;
  }
};
