export const goodMechanics = [
  { mechanic: "Resource Management" },
  { mechanic: "Turn-based Combat" },
  { mechanic: "Real-time Strategy" },
  { mechanic: "Inventory System" },
  { mechanic: "Crafting" },
  { mechanic: "Puzzle Solving" },
  { mechanic: "Stealth" },
  { mechanic: "Dialogue Choices" },
  { mechanic: "Multiple Endings" },
  { mechanic: "Platforming" },
  { mechanic: "First-Person Shooter (FPS)" },
  { mechanic: "Third-Person Shooter (TPS)" },
  { mechanic: "Open World Exploration" },
  { mechanic: "Side Quests" },
  { mechanic: "Skill Trees" },
  { mechanic: "Leveling Up" },
  { mechanic: "Cooperative Gameplay (Co-op)" },
  { mechanic: "Competitive Multiplayer" },
  { mechanic: "Time Management" },
  { mechanic: "Physics-based Gameplay" },
  { mechanic: "Rhythm/Music-Based" },
  { mechanic: "Survival Mechanics" },
  { mechanic: "Building and Construction" },
  { mechanic: "Tower Defense" },
  { mechanic: "Point-and-Click Adventure" },
  { mechanic: "Roguelike Elements" },
  { mechanic: "Procedural Generation" },
  { mechanic: "Quick Time Events (QTEs)" },
  { mechanic: "Moral Decision Making" },
  { mechanic: "Vehicle Simulation" },
  { mechanic: "Farming and Management" },
  { mechanic: "Narrative-Driven" },
  { mechanic: "Puzzle Platformer" },
  { mechanic: "Turn-Based Tactics" },
  { mechanic: "Hack and Slash" },
  { mechanic: "Text-Based Adventure" },
  { mechanic: "Visual Novel Elements" },
  { mechanic: "Match-Three Puzzle" },
  { mechanic: "Bullet Hell" },
  { mechanic: "Parkour Mechanics" },
  { mechanic: "Virtual Reality (VR) Support" },
  { mechanic: "Augmented Reality (AR) Elements" },
  { mechanic: "Asymmetric Gameplay" },
  { mechanic: "Environmental Storytelling" },
  { mechanic: "Permadeath" },
  { mechanic: "Card Battle System" },
  { mechanic: "Dynamic Weather System" },
  { mechanic: "Day/Night Cycle" },
  { mechanic: "AI Companions" },
  { mechanic: "Non-linear Gameplay" },
  { mechanic: "Character Customization" },
  { mechanic: "Base Building" },
  { mechanic: "Sandbox Gameplay" },
  { mechanic: "Minigames" },
  { mechanic: "Gesture-based Controls" },
  { mechanic: "Photo Mode" },
  { mechanic: "Educational Elements" },
  { mechanic: "Physics Puzzles" },
  { mechanic: "Retro-inspired Graphics" },
  { mechanic: "Multiplayer Online Battle Arena (MOBA)" },
  { mechanic: "Battle Royale" },
  { mechanic: "Massively Multiplayer Online (MMO)" },
  { mechanic: "Local Multiplayer" },
  { mechanic: "Dynamic AI" },
  { mechanic: "Loot System" },
  { mechanic: "Trading System" },
  { mechanic: "Dialogue System with Voice Acting" },
  { mechanic: "Branching Storylines" },
  { mechanic: "Craftable Weapons and Gear" },
  { mechanic: "Automated Resource Gathering" },
  { mechanic: "Time Travel Mechanics" },
  { mechanic: "Alternate Reality Game (ARG) Elements" },
  { mechanic: "Fitness and Exercise Integration" },
  { mechanic: "Social Networking Features" },
  { mechanic: "Cloud Gaming Support" },
  { mechanic: "Cross-platform Play" },
  { mechanic: "Mod Support and Community Mods" },
  { mechanic: "Esports Elements" },
  { mechanic: "Narrative Choices Impacting Gameplay" },
  { mechanic: "Dynamic Difficulty Adjustment" },
  { mechanic: "Steampunk Aesthetic" },
  { mechanic: "Fantasy Themes" },
  { mechanic: "Science Fiction Elements" },
  { mechanic: "Historical Settings" },
  { mechanic: "Horror and Survival Elements" },
];

export const badMechanics = [
  { mechanic: "Resource Management" },
  { mechanic: "Turn-based Combat" },
  { mechanic: "Real-time Strategy" },
  { mechanic: "Inventory System" },
  { mechanic: "Crafting" },
  { mechanic: "Puzzle Solving" },
  { mechanic: "Stealth" },
  { mechanic: "Dialogue Choices" },
  { mechanic: "Multiple Endings" },
  { mechanic: "Platforming" },
  { mechanic: "First-Person Shooter (FPS)" },
  { mechanic: "Third-Person Shooter (TPS)" },
  { mechanic: "Open World Exploration" },
  { mechanic: "Side Quests" },
  { mechanic: "Skill Trees" },
  { mechanic: "Leveling Up" },
  { mechanic: "Cooperative Gameplay (Co-op)" },
  { mechanic: "Competitive Multiplayer" },
  { mechanic: "Time Management" },
  { mechanic: "Physics-based Gameplay" },
  { mechanic: "Rhythm/Music-Based" },
  { mechanic: "Survival Mechanics" },
  { mechanic: "Building and Construction" },
  { mechanic: "Tower Defense" },
  { mechanic: "Point-and-Click Adventure" },
  { mechanic: "Roguelike Elements" },
  { mechanic: "Procedural Generation" },
  { mechanic: "Quick Time Events (QTEs)" },
  { mechanic: "Moral Decision Making" },
  { mechanic: "Vehicle Simulation" },
  { mechanic: "Farming and Management" },
  { mechanic: "Narrative-Driven" },
  { mechanic: "Puzzle Platformer" },
  { mechanic: "Turn-Based Tactics" },
  { mechanic: "Hack and Slash" },
  { mechanic: "Text-Based Adventure" },
  { mechanic: "Visual Novel Elements" },
  { mechanic: "Match-Three Puzzle" },
  { mechanic: "Bullet Hell" },
  { mechanic: "Parkour Mechanics" },
  { mechanic: "Virtual Reality (VR) Support" },
  { mechanic: "Augmented Reality (AR) Elements" },
  { mechanic: "Asymmetric Gameplay" },
  { mechanic: "Environmental Storytelling" },
  { mechanic: "Permadeath" },
  { mechanic: "Card Battle System" },
  { mechanic: "Dynamic Weather System" },
  { mechanic: "Day/Night Cycle" },
  { mechanic: "AI Companions" },
  { mechanic: "Non-linear Gameplay" },
  { mechanic: "Character Customization" },
  { mechanic: "Base Building" },
  { mechanic: "Sandbox Gameplay" },
  { mechanic: "Minigames" },
  { mechanic: "Gesture-based Controls" },
  { mechanic: "Photo Mode" },
  { mechanic: "Educational Elements" },
  { mechanic: "Physics Puzzles" },
  { mechanic: "Retro-inspired Graphics" },
  { mechanic: "Multiplayer Online Battle Arena (MOBA)" },
  { mechanic: "Battle Royale" },
  { mechanic: "Massively Multiplayer Online (MMO)" },
  { mechanic: "Local Multiplayer" },
  { mechanic: "Dynamic AI" },
  { mechanic: "Loot System" },
  { mechanic: "Trading System" },
  { mechanic: "Dialogue System with Voice Acting" },
  { mechanic: "Branching Storylines" },
  { mechanic: "Craftable Weapons and Gear" },
  { mechanic: "Automated Resource Gathering" },
  { mechanic: "Time Travel Mechanics" },
  { mechanic: "Alternate Reality Game (ARG) Elements" },
  { mechanic: "Fitness and Exercise Integration" },
  { mechanic: "Social Networking Features" },
  { mechanic: "Cloud Gaming Support" },
  { mechanic: "Cross-platform Play" },
  { mechanic: "Mod Support and Community Mods" },
  { mechanic: "Esports Elements" },
  { mechanic: "Narrative Choices Impacting Gameplay" },
  { mechanic: "Dynamic Difficulty Adjustment" },
  { mechanic: "Steampunk Aesthetic" },
  { mechanic: "Fantasy Themes" },
  { mechanic: "Science Fiction Elements" },
  { mechanic: "Historical Settings" },
  { mechanic: "Horror and Survival Elements" },
];

export const getRandomMechanic = () => {
  const combineMechanics = Math.random() < 0.5;

  if (combineMechanics) {
    const goodMechanic =
      goodMechanics[Math.floor(Math.random() * goodMechanics.length)];
    const badMechanic =
      badMechanics[Math.floor(Math.random() * badMechanics.length)];

    return `${goodMechanic.mechanic} and ${badMechanic.mechanic}`;
  } else {
    const allMechanics = [...goodMechanics, ...badMechanics];
    const mechanic =
      allMechanics[Math.floor(Math.random() * allMechanics.length)].mechanic;

    return mechanic;
  }
};
