export const goodModifiers = [
  { modifier: "Limited Capacity" },
  { modifier: "You Are the Weapon" },
  { modifier: "Inverse Controls" },
  { modifier: "Time Constraints" },
  { modifier: "Permadeath" },
  { modifier: "No Jumping Allowed" },
  { modifier: "Double Damage" },
  { modifier: "Randomized Levels" },
  { modifier: "Single Life" },
  { modifier: "Invisibility" },
  { modifier: "Silent Mode (No Sound)" },
  { modifier: "Zero Gravity" },
  { modifier: "Limited Visibility" },
  { modifier: "One Hit, One Kill" },
  { modifier: "Constant Health Drain" },
  { modifier: "Ammo Scarcity" },
  { modifier: "Random Power-Ups" },
  { modifier: "Enemies Respawn" },
  { modifier: "Unstable Terrain" },
  { modifier: "Friendly Fire Enabled" },
  { modifier: "Random Teleportation" },
  { modifier: "Upside-Down World" },
  { modifier: "Mirrored Levels" },
  { modifier: "Super Speed" },
  { modifier: "Slow Motion" },
  { modifier: "Automatic Level Progression" },
  { modifier: "Randomized Objectives" },
  { modifier: "Volatile Environment" },
  { modifier: "No Healing" },
  { modifier: "Energy-Based Movement" },
  { modifier: "Inverted Physics" },
  { modifier: "Labyrinthine Maps" },
  { modifier: "Mandatory Stealth" },
  { modifier: "Fragile Environment" },
  { modifier: "Random Enemy Strength" },
  { modifier: "Sudden Weather Changes" },
  { modifier: "Limited Weapon Usage" },
  { modifier: "Pacifism Mode (No Killing)" },
  { modifier: "Hunger and Thirst" },
  { modifier: "Randomized Player Abilities" },
  { modifier: "Unpredictable AI" },
  { modifier: "Augmented Reality Integration" },
  { modifier: "Real-Time Aging" },
  { modifier: "Morphing Terrain" },
  { modifier: "Evolving Game Rules" },
  { modifier: "Reality Warping" },
  { modifier: "Mind Control Mechanics" },
  { modifier: "Chaotic Magic Effects" },
  { modifier: "Shifting Objectives" },
  { modifier: "Disappearing Platforms" },
  { modifier: "Limited Resource Management" },
  { modifier: "Invisible Obstacles" },
  { modifier: "Reverse Level Progression" },
  { modifier: "Clone Enemies" },
  { modifier: "Darkness Mode" },
  { modifier: "Weightless Objects" },
  { modifier: "Random Player Size Change" },
  { modifier: "Distorted Perspectives" },
  { modifier: "Shared Player Health" },
  { modifier: "Chaotic Time Loops" },
  { modifier: "Disrupted Communication" },
  { modifier: "Illusionary World" },
  { modifier: "Randomized Control Scheme" },
  { modifier: "Telekinetic Powers Only" },
  { modifier: "Gravity Shifts" },
  { modifier: "Dimensional Shifting" },
  { modifier: "Color-Based Mechanics" },
  { modifier: "Sound Sensitive Environment" },
  { modifier: "Elemental Disturbances" },
  { modifier: "Living Environment" },
  { modifier: "Unstable Power-Ups" },
  { modifier: "Mystical Transformations" },
  { modifier: "Dancing Required" },
  { modifier: "Sing to Progress" },
  { modifier: "Memory-Based Puzzles" },
  { modifier: "Empathy Gameplay (Feel Enemies' Emotions)" },
  { modifier: "Abstract Reality" },
  { modifier: "Dream Logic Puzzles" },
  { modifier: "Mandatory Cooperation" },
  { modifier: "Randomized Physics Laws" },
  { modifier: "Contagious Effects" },
  { modifier: "Role Reversal" },
  { modifier: "Narrative Puzzles" },
  { modifier: "Hidden Game Rules" },
  { modifier: "Player-Controlled Environment" },
];

export const getRandomModifier = () => {
  const randomIndex = Math.floor(Math.random() * goodModifiers.length);
  return goodModifiers[randomIndex].modifier;
};
