export const soundThemes = [
  { musicTheme: "80s Synthwave" },
  { musicTheme: "Orchestral Fantasy" },
  { musicTheme: "Silent Movie Piano" },
  { musicTheme: "Epic Space Opera" },
  { musicTheme: "Medieval Folk" },
  { musicTheme: "Jazz Noir" },
  { musicTheme: "Cyberpunk Electronic" },
  { musicTheme: "Chiptune Arcade" },
  { musicTheme: "Mystical Ambience" },
  { musicTheme: "Heavy Metal Power" },
  { musicTheme: "Retro 8-bit" },
  { musicTheme: "Classical Baroque" },
  { musicTheme: "Modern Pop" },
  { musicTheme: "Grunge Rock" },
  { musicTheme: "Tropical Island Rhythms" },
  { musicTheme: "Horror and Suspense" },
  { musicTheme: "Country Western" },
  { musicTheme: "Calm Lo-Fi" },
  { musicTheme: "Traditional Asian" },
  { musicTheme: "Middle Eastern Melodies" },
  { musicTheme: "African Drums and Percussion" },
  { musicTheme: "Reggae Beats" },
  { musicTheme: "Futuristic Techno" },
  { musicTheme: "Underground Hip-Hop" },
  { musicTheme: "Viking War Chants" },
  { musicTheme: "Celtic Flutes" },
  { musicTheme: "Latin Salsa" },
  { musicTheme: "Deep Sea Echoes" },
  { musicTheme: "Disco Funk" },
  { musicTheme: "Wildlife Nature Sounds" },
  { musicTheme: "Majestic Choir" },
  { musicTheme: "Pirate Shanties" },
  { musicTheme: "Soothing Meditation" },
  { musicTheme: "Post-Rock Atmospheric" },
  { musicTheme: "Steampunk Mechanical Beats" },
  { musicTheme: "Indie Acoustic" },
  { musicTheme: "Space Ambient" },
  { musicTheme: "Urban Street Style" },
  { musicTheme: "Romantic Classical" },
  { musicTheme: "Desert Winds" },
  { musicTheme: "Mystery and Intrigue" },
  { musicTheme: "Gothic Organ" },
  { musicTheme: "Adventure Epic" },
  { musicTheme: "Surreal Dreamscapes" },
  { musicTheme: "Renaissance Faire" },
  { musicTheme: "Smooth Jazz" },
  { musicTheme: "Hard Rock Energy" },
  { musicTheme: "Christmas Jingles" },
  { musicTheme: "Victorian Era Ballroom" },
  { musicTheme: "Ancient Tribal" },
  { musicTheme: "Sci-Fi Synthesizers" },
  { musicTheme: "K-Pop Energy" },
  { musicTheme: "Vaporwave Aesthetics" },
  { musicTheme: "Old West Duel" },
  { musicTheme: "Haunted Gothic Choir" },
  { musicTheme: "Arctic Chills" },
  { musicTheme: "Ragtime Piano" },
  { musicTheme: "Retro Futurism" },
  { musicTheme: "Heroic Orchestration" },
  { musicTheme: "Underworld Ambiance" },
  { musicTheme: "Bollywood Vibrance" },
  { musicTheme: "Greek Folklore" },
  { musicTheme: "Carnival and Circus" },
  { musicTheme: "Punk Rock Rebellion" },
  { musicTheme: "Jungle Rhythms" },
  { musicTheme: "Experimental Electronica" },
];

export const getRandomSoundTheme = () => {
  return soundThemes[Math.floor(Math.random() * soundThemes.length)].musicTheme;
};
